### ISSUE TITLE
Tweak "Top games" filter 

### ISSUE THREAD

**Issue by TBestLittleHelper** [lichess-org/lila-openingexplorer#202]
Discord ref : https://discord.com/channels/280713822073913354/1059565901034295387/1059565901034295387

To recap, after the lichess database started indexing all played games, the current top games filter is not strict enough. When we want to show games played by extremely strong players - currently it will often select players that are "only" 2500.  

- Consider a dynamic top games filter: where more common positions have a stricter definition of "top"
- Maybe rename "top games". Top games might imply that it's only sorted by rating - but in practice it's more factors.

**Comment by niklasf** [comment]
First attempt deployed.

**Comment by niklasf** [comment]
After https://github.com/lichess-org/lila/issues/13790, top games can now just come from the highest [rating group (i.e., the filters plus some internal groups)](https://github.com/lichess-org/lila-openingexplorer/blob/a762906ebca83396984d5a8307401ff8f5222d73/src/model/lichess.rs#L29-L33) for the time control. The thresholds could be tweaked further whenever we next reindex the games.
