### ISSUE TITLE
Chess game in the master database is not actually a chess game

### ISSUE THREAD

**Issue by alkamaass** [lichess-org/lila-openingexplorer#215]
This is regarding the only master database game where the Jerome gambit is played. https://lichess.org/cT38OW6n

This game obviously makes little sense especially at this rating, and there is a very good explanation, it is not actually a game of chess, it is a chess variant. This somehow made its way into the database. Obviously if this game got into the database, it is very concerning as that means there are probably other games where it is not vanilla chess but rather a variant. All the documentation and evidence proving that this game is not a vanilla chess game and should be removed immediately is here: [https://jeromegambit.blogspot.com/2021/02/where-jerome-goes-strangeness-follows.htm](https://jeromegambit.blogspot.com/2021/02/where-jerome-goes-strangeness-follows.htm)

**Comment by niklasf** [comment]
Thanks for reporting. I have removed it from our internal database (https://github.com/lichess-org/masters-db/commit/37341a4a6daaf3d4f54fc24b8c2c92b525dcbebe), which will eventually be used to build the next revision of the Masters database.
