### ISSUE TITLE
No games for August 2023 (+September 2023?)

### ISSUE THREAD

**Issue by AAArmstark** [lichess-org/lila-openingexplorer#241]
It was first reported [here](https://lichess.org/forum/lichess-feedback/lichess-database-bug) and I couldn't find an explanation for it (maybe it takes some time to update on the 1st of a month or whatever) and thought it's better to report it.

Steps to reproduce:

1. Go to [opening explorer](https://lichess.org/analysis#explorer)
2. In the settings, select "Lichess database"
3. Set "Since" to "August 2023"
4. Set "Until" to "August 2023" or "September 2023"
5. Check that every rating/time control is selected
6. "No game found" message showing up

**Comment by niklasf** [comment]
Hi, yes, this is expected. To explain:

The process is currently to wait for the export of the month on https://database.lichess.org/, followed by downloading and importing the database dump on the opening explorer server. The opening explorer server has just enough I/O throughput to handle requests at peak time, so the import process is throttled to avoid putting too much load on it. All in all games can be up to 6 weeks late.

The same is not true for the "personal"/player, which is updated on demand but almost immediately.

**Comment by AAArmstark** [comment]
Thanks for the detailed answer and sorry for taking up your time!
