### ISSUE TITLE
Chess game that is not following the rules of chess previously removed, and then added again to masters database

### ISSUE THREAD

**Issue by alkamaass** [lichess-org/lila-openingexplorer#285]
This is regarding the only master database game where the Jerome gambit is played. https://lichess.org/cT38OW6n  

I made a previous github issue over a year ago calling for this game to be removed, it got removed but then got added again?!?!? 
Where is this game that is obviously not chess coming from!?!? It should not be in the database ever.

This game obviously makes little sense especially at this rating, and there is a very good explanation, it is not actually a game of chess, it is a chess variant where you can veto moves. This somehow made its way into the database. Obviously if this game got into the database (TWICE?!?!?!), it is very concerning as that means there are probably other games where it is not vanilla chess but rather a variant. All the documentation and evidence proving that this game is not a vanilla chess game and should be removed immediately is here: 

https://jeromegambit.blogspot.com/2021/02/where-jerome-goes-strangeness-follows.html

**Comment by niklasf** [comment]
Previous issue: #215. It was never actually removed from the live database. That will happen in batch with many other changes, when the master database is reindexed/rebuilt. I know it's been a long time, but it will happen eventually.

**Comment by alkamaass** [comment]
Thanks, I hope that happens soon because I think that only chess games belong in there not chess variants
