### ISSUE TITLE
Games by the current user

### ISSUE THREAD

**Issue by niklasf** [lichess-org/lila-openingexplorer#63]
As requested sometimes:
* ornicar/lila#5589
* ornicar/lila#1863
* ornicar/lila#6170
* ornicar/lila#6287

**Comment by dejlek** [comment]
Is this ever going to be merged. This is really useful feature so that I can look at what humans typically play in certain lines...

**Comment by niklasf** [comment]
Maybe. The priority is pretty low, because https://www.openingtree.com/ is another open source site that does it very well, and it supports importing games from Lichess.

**Comment by niklasf** [comment]
Today via https://github.com/niklasf/lila-openingexplorer3. UI improvements tracked in https://github.com/ornicar/lila/issues/9990.
